---
- name: Install prerequisites on all hosts and gather facts
  hosts: all:!undercloud_host
  tags:
    - prereqs
  roles:
    - firewall/gather
    - prereqs
    - repos
    - chrony

- name: Install ElasticSearch
  hosts: elastic_hosts
  tags:
    - logging
    - elasticsearch
  roles:
    - elasticsearch/server

- name: Install Fluentd
  hosts: fluent_hosts
  tags:
    - logging
    - fluentd
  roles:
    - fluentd/server
    - fluentd/syslog
    - fluentd/elasticsearch

- name: Install Kibana
  hosts: kibana_hosts
  tags:
    - logging
    - kibana
    - web
  roles:
    - kibana/server
    - kibana/proxy
